yatube/about/urls.py
from django.urls import path

from . import views


app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'
urlpatterns = [
    path('posts/<post_id>/edit/', views.post_edit, name='edit'),
    path('create/', views.post_create, name='create'),
    path('group/<slug:slug>/', views.group_posts, name='group_posts'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('posts/<int:post_id>/comment/',
         views.add_comment, name='add_comment'
         ),
    path('', views.index, name='index'),
    path('follow/', views.follow_index, name='follow_index'),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow'
    ),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('about/', include('about.urls', namespace='about')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('', include('posts.urls', namespace='posts')),
]

handler404 = 'core.views.page_not_found'

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/posts/models.py
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()


class Group(models.Model):
    title = models.CharField(
        max_length=200,
        verbose_name='Заголовок',
    )

    slug = models.SlugField(unique=True)

    description = models.TextField(
        max_length=400,
        verbose_name='Описание группы',
        help_text="введите описание группы (максимум 400 символов)"
    )

    def __str__(self):
        return self.title

    class Meta:
        verbose_name_plural = 'Группы'
        verbose_name = 'группы'


class Post(models.Model):
    text = models.TextField(
        verbose_name='Текст поста',
    )

    pub_date = models.DateTimeField(
        auto_now_add=True,
        verbose_name='Дата публикации',
    )

    author = models.ForeignKey(
        User,
        max_length=30,
        on_delete=models.CASCADE,
        related_name='posts',
        verbose_name='Автор',
    )

    group = models.ForeignKey(
        Group,
        on_delete=models.SET_NULL,
        related_name='posts',
        verbose_name='Принадлежность к группе',
        null=True,
        blank=True,
    )

    image = models.ImageField(
        verbose_name='Изображение',
        upload_to='posts/',
        blank=True,
    )

    def __str__(self):
        return self.text[:1000]

    class Meta:
        ordering = ['-pub_date']
        verbose_name_plural = 'Посты'
        verbose_name = 'Пост'


class Comment(models.Model):
    post = models.ForeignKey(
        Post,
        related_name='comments',
        verbose_name='Пост',
        on_delete=models.CASCADE,
    )

    author = models.ForeignKey(
        User,
        related_name='comments',
        verbose_name='Автор',
        on_delete=models.CASCADE,
    )

    text = models.TextField(
        verbose_name='Комментарий',
    )

    data_created = models.DateTimeField(
        auto_now=True,
        verbose_name='Дата создания',
    )

    data_updated = models.DateTimeField(
        auto_now=True,
        verbose_name='Дата обновления',
    )

    def __str__(self):
        return self.text[:100]

    class Meta:
        ordering = ['-data_created']
        verbose_name = 'Комментарий'


class Follow(models.Model):
    # пользователь, который подписывается
    user = models.ForeignKey(
        User,
        related_name='follower',
        on_delete=None
    )
    # пользователь, на которого подписывются
    author = models.ForeignKey(
        User,
        related_name='following',
        on_delete=models.CASCADE
    )

yatube/posts/forms.py
from django import forms

from .models import Comment, Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['text', 'group', 'image']
        help_texts = {
            'text': 'Текст нового поста',
            'group': 'Группа, к которой будет относится пост',
            'image': 'выбрать картинку',
        }


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['text']
        help_text = {
            'text': 'Текст поста'
        }

yatube/posts/views.py
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.conf import settings
from django.shortcuts import get_object_or_404, redirect, render

from .forms import CommentForm, PostForm
from .models import Comment, Follow, Group, Post, User


def addition_paginator(queryset, request):
    # Внедрение паджинатора
    paginator = Paginator(queryset, settings.NUM_OF_POSTS)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    return {'page_obj': page_obj}


def index(request):
    # Главная страница
    post_list = Post.objects.all()
    template = 'posts/index.html'
    context_title = addition_paginator(post_list, request)
    return render(request, template, context_title)


def group_posts(request, slug):
    # Групповая страница
    group = get_object_or_404(Group, slug=slug)
    groups = group.posts.all()
    template = 'posts/group_list.html'
    context = {
        'group': group,
        'posts': groups,
    }
    context.update(addition_paginator(groups, request))
    return render(request, template, context)


def profile(request, username):
    # Страница профиля
    author = get_object_or_404(User, username=username)
    posts = author.posts.all()
    following = request.user.is_authenticated
    if following:
        following = author.following.filter(user=request.user).exists()
    template = 'posts/profile.html'
    context = {
        'author': author,
        'following': following
    }
    context.update(addition_paginator(posts, request))
    return render(request, template, context)


def post_detail(request, post_id):
    # Подробная информация о посте
    post = get_object_or_404(Post, id=post_id)
    form = CommentForm(request.POST or None)
    comments = Comment.objects.filter(post=post)
    context = {
        'post': post,
        'form': form,
        'comments': comments,
    }
    template = 'posts/post_detail.html'
    return render(request, template, context)


@login_required
def post_create(request):
    # Создание поста
    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
    )
    if form.is_valid():
        create_post = form.save(commit=False)
        create_post.author = request.user
        create_post.save()
        return redirect('posts:profile', create_post.author)
    template = 'posts/create_post.html'
    context = {'form': form}
    return render(request, template, context)


@login_required
def post_edit(request, post_id):
    # Редактирование поста
    edit_post = get_object_or_404(Post, id=post_id)
    if request.user != edit_post.author:
        return redirect('posts:post_detail', post_id)
    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
        instance=edit_post
    )
    if form.is_valid():
        form.save()
        return redirect('posts:post_detail', post_id)
    template = 'posts/create_post.html'
    context = {'form': form, 'is_edit': True}
    return render(request, template, context)


@login_required
def add_comment(request, post_id):
    # Добавление комментария
    post = get_object_or_404(Post, id=post_id)
    form = CommentForm(request.POST or None)
    comments = Comment.objects.filter(post=post)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
        return redirect('posts:post_detail', post_id=post_id)

    context = {
        'post': post,
        'form': form,
        'comments': comments,
    }
    return render(request, 'posts:post_detail', context)


@login_required
def follow_index(request):
    posts = Post.objects.filter(
        author__following__user=request.user)
    context = addition_paginator(posts, request)
    template = 'posts/follow.html'
    return render(request, template, context)


@login_required
def profile_follow(request, username):
    # Подписка
    author = get_object_or_404(User, username=username)
    if author != request.user:
        Follow.objects.get_or_create(user=request.user, author=author)
    template = 'posts:profile'
    return redirect(template, author)


@login_required
def profile_unfollow(request, username):
    # Отписка
    user_follower = get_object_or_404(
        Follow,
        user=request.user,
        author__username=username
    )
    user_follower.delete()
    template = 'posts:profile'
    return redirect(template, username)

yatube/templates/posts/create_post.html
{% extends "base.html" %}

{% block title %}Новый пост{% endblock %}

{% block content %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">{% if is_edit %}Редактировать запись{% else %}Добавить запись{% endif %}</div>
        <div class="card-body">
            {% include 'includes/form.html' %}
            <div class="d-flex justify-content-end">
              <button type="submit" class="btn btn-primary">{% if is_edit %}Сохранить{% else %}Добавить{% endif %}</button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

yatube/templates/posts/follow.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %}Подписки{% endblock %}

{% block content %}

<div class="container py-5">
  <div class="content-info">
    <h1><center>Последние обновления на сайте</center></h1>
    {% include 'includes/switcher.html' with follow=True %}

    {% for post in page_obj %}
      <ul class="list-group">
        <li class="list-group-item list-group-item-light">
          Автор: <a href="{% url 'posts:profile' post.author %}">
          {% if post.author.get_full_name %}{{ post.author.get_full_name }}{% else %}{{ post.author }}{% endif %}
          </a>
        </li>
        <li class="list-group-item list-group-item-light">
          Дата публикации: <strong>{{ post.pub_date|date:'d E Y' }}</strong>
        </li>
      </ul>

    <div class="card bg-light", style="width: 100%">
      {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
        <div class="image-content-mini"></div>
          <img class="card-img-top" src="{{ im.url }}">
        </div>
      {% endthumbnail %}
      <div class="card-body">
        <h4 class="card-title">Заголовок</h4>
        <p class="card-text">{{ post.text|linebreaksbr }}</p>
        <a href="{% url 'posts:post_detail' post.id %}" class="btn btn-primary">Подробная информация</a>

        {% if post.group %}
          <a href="{% url 'posts:group_posts' post.group.slug %}" class="btn btn-primary">Все записи группы "{{ post.group }}"</a>
        {% endif %}
      </div>
    </div>

    {% if not forloop.last %}<hr>{% endif %}
    {% endfor %}
    <div class="d-flex justify-content-center">
      {% include 'includes/paginator.html' %}
    </div>
  </div>
</div>
{% endblock %}

yatube/templates/posts/group_list.html
{% extends "base.html" %}
{% load thumbnail %}

{% block title %}
  Записи сообщества {{ group.title }}
{% endblock %}

{% block content %}
  <div class="container py-5">
    <div class="content-info">
    <h1>{{ group.title }}</h1>
    <p>{{ group.description }}</p>
    {% for post in page_obj %}
      <ul>
        <li>
          Автор: {% if post.author.get_full_name %}{{ post.author.get_full_name }}{% else %}{{ post.author }}{% endif %} <a href="{% url 'posts:profile' post.author %}">все посты пользователя</a>
        </li>
        <li class=entry>
          Дата публикации: {{ post.pub_date|date:"d E Y" }}
        </li>
      </ul>
      <div class="image-content-mini">{% thumbnail post.image "400x400" crop="center" upscale=True as im %}
        <img class="card-img my-2" src="{{ im.url }}">{% endthumbnail %}
      </div>
      <p>{{ post.text }}</p>
      {% if not forloop.last %}
        <hr>
      {% endif %}
    {% endfor %}
    </div>
    {% include 'includes/paginator.html' %}
  </div>
{% endblock %}

yatube/templates/posts/index.html
{% extends "base.html" %}
{% load thumbnail %}
{% load cache %}

{% block title %}
  Главная страница
{% endblock %}

{% block content %} 
  <div class="container py-5">
    <div class="content-info">
      <h1><center>Последние обновления на сайте</center></h1>

      {% cache 20 index_page page_obj.number %}

      {% include 'includes/switcher.html' %}
      {% for post in page_obj %}
        <ul>
          <li>
            <h4>
              Автор: {% if post.author.get_full_name %}{{ post.author.get_full_name }}{% else %}{{ post.author }}{% endif %} <a href="{% url 'posts:profile' post.author %}">все посты пользователя</a>
            </h4>
          </li>
          <li>
            Дата публикации: {{ post.pub_date|date:"d E Y" }}
          </li>
        </ul>
      <div class="image-content-mini">
          {% thumbnail post.image "400x400" crop="center" upscale=True as im %}
            <img class="card-img my-2" src="{{ im.url }}">
          {% endthumbnail %}
      </div>
        <p>{{ post.text }}</p>
         <a href="{% url 'posts:post_detail' post.id %}">подробная информация о посте</a>
        {% if post.group %}
          <p align="right">
          <a href="{% url 'posts:group_posts' post.group.slug %} "><font color='black'>
          все записи группы</font>
          </a>
          </p>
        {% endif %}
        {% if not forloop.last %}<hr>{% endif %}

      {% endfor %}

      {% endcache %}
      {% include 'includes/paginator.html' %}
    </div>
    </div>
{% endblock %}

yatube/templates/posts/post_detail.html
{% extends "base.html" %}
{% load thumbnail %}
{% load user_filters %}

{% block title %}Пост {{ post|truncatechars:30 }}{% endblock %}

{% block content %}
  <div class="row">
    <aside class="col-12 col-md-3">
      <ul class="list-group list-group-flush">
        <li class="list-group-item">
          Дата публикации: {{ post.pub_date|date:'d E Y' }}
        </li>
        <li class="list-group-item">
          Группа:
          {% if post.group %}
            {{ post.group }}
          {% else %}
            ---Пусто---
          {% endif %}
          {% if post.group %}
            <a href="{% url 'posts:group_posts' post.group.slug %}">все записи группы</a>
          {% endif %}
        </li>
        <li class="list-group-item">
          Автор: {% if post.author.get_full_name %}{{ post.author.get_full_name }}{% else %}{{ post.author }}{% endif %}
        </li>
        <li class="list-group-item">
          Всего постов автора: {{ post.author.posts.all.count }}
        </li>
        <li class="list-group-item">
          <a href="{% url 'posts:profile' post.author %}">все посты пользователя</a>
        </li>
      </ul>
    </aside>
    <article class="col-12 col-md-9">
      <div class="post-in-post-detail">
        <div class="image-content">
          <center>
          {% thumbnail post.image "400x400" crop="center" upscale=True as im %}
            <img class="card-img my-2" src="{{ im.url }}">
          {% endthumbnail %}
          </center>
        </div>
        <p>{{ post }}</p>
        <div class="post-in-post-detail">
          {% if user.is_authenticated %}
          <div class="card my-4">
            <h5 class="card-header">Добавить комментарий:</h5>
              <div class="card-body">
                <form method="post" action="{% url 'posts:add_comment' post.id %}">{% csrf_token %}
                  <div class="form-group mb-2">
                    {{ form.text|addclass:"form-control" }}
                  </div>
                <button type="submit" class="btn btn-primary">Отправить</button>
                </form>
              </div>
          </div>
        {% endif %}

        {% for comment in comments %}
          <div class="media mb-4">
            <div class="media-body">
              <h5 class="mt-0">
                <a href="{% url 'posts:profile' comment.author.username %}">
                 {{ comment.author.username }}
                </a>
              </h5>
              <p>
                {{ comment.text }}
              </p>
            </div>
          </div>
        {% endfor %}
        </div>
      </div>
      {% if post.author == user %}
        <center> <a class="btn btn-primary" href="{% url 'posts:edit' post.id %}">редактировать запись</a>
      {% endif %}
    </article>
  </div>

{% endblock %}

yatube/templates/posts/profile.html
{% extends 'base.html' %}
{% load thumbnail %}

{% block title %}
 {{ author.get_full_name }}
{% endblock %}

{% block content %}
  <div class="container py-5">
    <div class="content-info">
    <h1>Все посты пользователя {{ author.get_full_name }} </h1>
    <h3>Всего постов: {{ author.post_list.all.count }} </h3>

      {% if following %}
        <a class="btn btn-lg btn-light" href="{% url 'posts:profile_unfollow' author.username %}" role="button">Отписаться</a>
      {% else %}
        <a class="btn btn-lg btn-primary" href="{% url 'posts:profile_follow' author.username %}" role="button">Подписаться</a>
   {% endif %}
  
    {% for post in page_obj %}
        <ul>
            <li>
              Дата публикации: {{ post.pub_date|date:'d E Y' }}
            </li>
        </ul>
        <div class="image-content">
          <center>
          {% thumbnail post.image "400x400" crop="center" upscale=True as im %}
            <img class="card-img my-2" src="{{ im.url }}">
          {% endthumbnail %}
          </center>
        </div>
        <p>{{ post.text }}</p>
        <a href="{% url 'posts:post_detail' post.id %}">подробная информация</a>
        <br>
        {% if post.group %}
            <a href="{% url 'posts:group_posts' post.group.slug %}">все записи группы</a>
        {% endif %}
        {% if not forloop.last %}<hr>{% endif %}
    {% endfor %}
    
      <div class="d-flex justify-content-center">
        <div>{% include 'includes/paginator.html' %}</div>
      </div>
    </div>
  </div>
{% endblock %}